server.port=8081
spring.application.name=migratediff-backend

file-storage.enabled=true
file-storage.root-path=${user.home}/.migratediff/storage

logging.file.path=${user.home}/.migratediff/logs

migratediff.presets[0].name=default-og
migratediff.presets[0].source.code=o-g
migratediff.presets[0].source.path=D:\\Coding\\code-compare-tools\\examples\\o
migratediff.presets[0].source.branch-from=refs/heads/o1
migratediff.presets[0].source.branch-to=refs/heads/o2
migratediff.presets[0].source.time-from=2025-11-01T00:00:00+08:00
migratediff.presets[0].source.time-to=2025-11-05T12:00:00+08:00
migratediff.presets[0].source.ref-hint=refs/heads/o2
migratediff.presets[0].source.delta-type=DELTA_O
migratediff.presets[0].source.include-working-tree=false
migratediff.presets[0].source.fetch-if-missing=true
migratediff.presets[0].source.remote-name=origin
migratediff.presets[0].target.code=g
migratediff.presets[0].target.path=D:\\Coding\\code-compare-tools\\examples\\g
migratediff.presets[0].target.branch-from=refs/heads/g1
migratediff.presets[0].target.branch-to=refs/heads/g2
migratediff.presets[0].target.time-from=2025-11-02T00:00:00+08:00
migratediff.presets[0].target.time-to=2025-11-05T12:00:00+08:00
migratediff.presets[0].target.ref-hint=refs/heads/g2
migratediff.presets[0].target.delta-type=DELTA_G
migratediff.presets[0].target.include-working-tree=false
migratediff.presets[0].target.fetch-if-missing=true
migratediff.presets[0].target.remote-name=origin
